#
# Docker Compose file for the Derafu Sites Server.
#
# This file is used to configure the docker container for the Derafu Sites Server.
#

# Name of the docker container.
name: ${SERVER_NAME:-derafu-sites-server}

# Services.
services:

  # Webserver container.
  webserver:

    # Build the container from the Dockerfile.
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWW_USER: ${ADMIN_USER:-admin}
        WWW_GROUP: ${ADMIN_GROUP:-www-data}
        WWW_ROOT_PATH: ${WWW_ROOT_PATH:-/var/www/sites}

    # Name of the container.
    container_name: ${SERVER_NAME:-derafu-sites-server}-php-caddy

    # Environment variables.
    environment:
      CADDY_DEBUG: ${CADDY_DEBUG:-}
      CADDY_EMAIL: ${CADDY_EMAIL:-admin@example.com}
      CADDY_LOG_SIZE: ${CADDY_LOG_SIZE:-100mb}
      CADDY_LOG_KEEP: ${CADDY_LOG_KEEP:-5}
      CADDY_LOG_KEEP_DAYS: ${CADDY_LOG_KEEP_DAYS:-14}
      CADDY_HTTPS_ISSUER: ${CADDY_HTTPS_ISSUER:-internal}
      WWW_ROOT_PATH: ${WWW_ROOT_PATH:-/var/www/sites}
      DEPLOYER_HOST: ${DEPLOYER_HOST:-}

    # Restart the container unless stopped.
    restart: unless-stopped

    # Ports mapping to the host.
    ports:
      - "${HTTP_PORT:-8080}:80"
      - "${HTTPS_PORT:-8443}:443"
      - "${SSH_PORT:-2222}:22"

    # Volumes.
    volumes:
      - ${VOLUME_SITES:-./sites}:${WWW_ROOT_PATH:-/var/www/sites}
      - ${VOLUME_DEPLOYER:-./deployer}:${DEPLOYER_DIR:-/home/admin/deployer}
